export interface MenuItem {
  id: number;
  name: string;
  price: number;
  is_available: boolean;
  category: string;
  position?: number; // Added position field
  image_url?: string; // Added image URL field
  description?: string; // Added description field
  // Inventory fields
  stock_quantity?: number;
  low_stock_threshold?: number;
  unit_type?: string;
  ingredients?: Record<string, number>; // ingredient: quantity
  supplier_info?: string;
  last_restocked?: string;
  // Raw materials
  raw_materials?: DishRawMaterial[];
}

export interface RawMaterial {
  id: number;
  name: string;
  description?: string;
  unit_type: string;
  current_stock: number;
  min_stock_level: number;
  supplier_info?: string;
  last_restocked?: string;
  created_at: string;
  updated_at: string;
}

export interface DishRawMaterial {
  id: number;
  dish_id: number;
  raw_material_id: number;
  quantity_required: number;
  raw_material?: RawMaterial;
  created_at: string;
  updated_at: string;
}

export interface RawMaterialUpdate {
  id: number;
  name?: string;
  description?: string;
  unit_type?: string;
  current_stock?: number;
  min_stock_level?: number;
  supplier_info?: string;
}

export interface DishRawMaterialUpdate {
  dish_id: number;
  raw_material_id: number;
  quantity_required: number;
}

export interface OrderItem extends MenuItem {
  quantity: number;
}

export interface Order {
  id: string;
  order_number: string;
  items: OrderItem[];
  total: number;
  status: 'pending' | 'preparing' | 'ready' | 'served' | 'cancelled';
  payment_status: 'pending' | 'paid' | 'failed';
  payment_mode?: 'cash' | 'online';
  order_time: string;
  updated_time?: string;
  table_code?: string;
  table_name?: string;
  order_type?: 'DINE_IN' | 'TAKEAWAY' | 'DELIVERY';
}

export interface CreateOrderRequest {
  order_number?: string; // Made optional as it will be generated by the API
  items: OrderItem[];
  total: number;
  order_type: 'DINE_IN' | 'TAKEAWAY' | 'DELIVERY';
  table_id?: string | null;
}

export interface UpdateOrderRequest {
  items?: OrderItem[];
  total?: number;
  status?: Order['status'];
  payment_status?: Order['payment_status'];
}

// Offline-first types
export interface LocalOrder {
  local_order_id: string;
  server_order_id?: string;
  order_number?: string;
  items: OrderItem[];
  total: number;
  status: 'pending' | 'preparing' | 'ready' | 'served' | 'cancelled';
  payment_status: 'pending' | 'paid' | 'failed';
  payment_mode?: 'cash' | 'online';
  order_time: string;
  order_type: 'DINE_IN' | 'TAKEAWAY' | 'DELIVERY';
  table_id?: string;
  table_code?: string;
  sync_status: 'pending' | 'syncing' | 'synced' | 'failed';
  sync_attempts: number;
  last_sync_attempt?: string;
  created_at: string;
  updated_at: string;
}

export interface LocalTable {
  id: number;
  table_code: string;
  table_name: string;
  capacity: number;
  is_active: boolean;
  is_occupied?: boolean;
  last_updated: string;
}

export interface SyncQueueItem {
  id: string;
  type: 'order_create' | 'order_update' | 'order_delete';
  local_order_id: string;
  data: any;
  created_at: string;
  retry_count: number;
  last_attempt?: string;
  error_message?: string;
}

export interface SyncResponse {
  success: boolean;
  server_order_id?: string;
  order_number?: string;
  error?: string;
}

// Customer authentication types
export interface Customer {
  id: number;
  name: string;
  mobile: string;
  created_at: string;
  updated_at: string;
}

export interface CustomerSignupRequest {
  name: string;
  mobile: string;
  password: string;
}

export interface CustomerLoginRequest {
  mobile: string;
  password: string;
}

export interface CustomerAuthResponse {
  customer: Customer;
  token: string;
}

export interface CustomerForgotPasswordRequest {
  mobile: string;
}

export interface Table {
  id: number;
  table_code: string;
  table_name: string;
  capacity: number;
  is_active: boolean;
  is_occupied?: boolean;
}
